# WIG20 dictionary
WIG20 = {
    'Orlen S.A.': 'PKN.WA',
    'CD Projekt S.A.': 'CDR.WA',
    'Alior Bank S.A.': 'ALR.WA',
    'Bank Polska Kasa Opieki S.A.': 'PEO.WA',
    'Bank Pekao S.A.': 'PEO.WA',
    'CCC S.A.': 'CCC.WA',
    'Cyfrowy Polsat S.A.': 'CPS.WA',
    'Grupa Lotos S.A.': 'LTS.WA',
    'Jastrzębska Spółka Węglowa S.A.': 'JSW.WA',
    'KGHM Polska Miedź S.A.': 'KGH.WA',
    'LPP S.A.': 'LPP.WA',
    'MBank S.A.': 'MBK.WA',
    'Orange Polska S.A.': 'OPL.WA',
    'PGE Polska Grupa Energetyczna S.A.': 'PGE.WA',
    'PKN Orlen S.A.': 'PKN.WA',
    'PZU S.A.': 'PZU.WA',
    'Santander Bank Polska S.A.': 'SPL.WA',
    'Tauron Polska Energia S.A.': 'TPE.WA',
    'Bank Handlowy w Warszawie S.A.': 'CMB.WA',
    'PKO Bank Polski S.A.': 'PKO.WA'
}

# mWIG40 dictionary
mWIG40 = {
    '11 bit studios S.A.': '11B.WA',
    'AB S.A.': 'ABE.WA',
    'ABK SA': 'ABK.WA',
    'AC SA': 'ACC.WA',
    'Aforti Holding S.A.': 'AFH.WA',
    'Agroton PLC': 'AGT.WA',
    'Aliplast spółka z ograniczoną odpowiedzialnością': 'ALP.WA',
    'Amica S.A.': 'AMC.WA',
    'Archicom S.A.': 'ARH.WA',
    'Asseco Poland S.A.': 'ACP.WA',
    'Atlas Ward Polska S.A.': 'AWP.WA',
    'ATM S.A.': 'ATM.WA',
    'Auto Partner S.A.': 'AUT.WA',
    'Bakoma S.A.': 'BKM.WA',
    'Benefit Systems S.A.': 'BFT.WA',
    'Bioton S.A.': 'BIO.WA',
    'Boryszew S.A.': 'BRS.WA',
    'Braster S.A.': 'BRC.WA',
    'Budimex S.A.': 'BDX.WA',
    'CCC S.A.': 'CCC.WA',
    'CD Projekt S.A.': 'CDR.WA',
    'Centrum Nowoczesnych Technologii S.A.': 'CNT.WA',
    'Ciech S.A.': 'CIE.WA',
    'CIG Pannonia Life Insurance S.A.': 'CIG.WA',
    'Columbus Energy S.A.': 'CEL.WA',
    'Cyfrowy Polsat S.A.': 'CPS.WA',
    'Cyrkon Group S.A.': 'CYR.WA',
    'Dino Polska S.A.': 'DNP.WA',
    'Dom Development S.A.': 'DOM.WA',
    'Duda S.A.': 'DUD.WA',
    'Dynamiki S.A.': 'DYN.WA',
    'Elektrobudowa S.A.': 'ELB.WA',
    'Enea S.A.': 'ENA.WA',
    'Enel-Med S.A.': 'ENE.WA',
    'Eurocash S.A.': 'EUR.WA',
    'Eurotel S.A.': 'ETL.WA',
    'Famur S.A.': 'FMF.WA',
    'Fon S.A.': 'FON.WA',
    'Forte S.A.': 'FTE.WA',
    'Future Processing S.A.': 'FPC.WA',
    'Getin Noble Bank S.A.': 'GNB.WA',
    'Globe Trade Centre S.A.': 'GTC.WA',
    'GPW S.A.': 'GPW.WA',
    'Griffin Premium RE S.A.': 'GRI.WA',
    'Gryphon Minerals Polska S.A.': 'GRY.WA',
    'Harper Hygienics S.A.': 'HHR.WA',
    'Haitong Bank S.A.': 'HIT.WA',
    'Helio S.A.': 'HEL.WA',
    'Hugon S.A.': 'HGN.WA',
    'IDEON S.A.': 'IDN.WA',
    'Impact Research Management S.A.': 'IMP.WA',
    'IndygoTech Minerals S.A.': 'IDG.WA',
    'InPost S.A.': 'POS.WA',
    'Inter Cars S.A.': 'CAR.WA',
    'Interferie S.A.': 'INF.WA',
    'JSW S.A.': 'JSW.WA',
    'KBD S.A.': 'KBD.WA',
    'Kernel Holding S.A.': 'KER.WA',
    'KGHM Polska Miedź S.A.': 'KGH.WA',
    'LCC Corporation S.A.': 'LCC.WA',
    'LC Corp S.A.': 'LCP.WA',
    'Lem SA': 'LEM.WA',
    'Leroy Merlin Polska S.A.': 'LMP.WA',
    'Lubawa S.A.': 'LBW.WA',
    'LUG S.A.': 'LUG.WA',
    'Lumena Energetyka S.A.': 'LEM.WA',
    'LUX MED Group S.A.': 'LMG.WA',
    'LW Bogdanka S.A.': 'LWB.WA',
    'Magellan S.A.': 'MGN.WA',
    'Makarony Polskie S.A.': 'MAK.WA',
    'Makroterm S.A.': 'MKO.WA',
    'Mango Media S.A.': 'MNG.WA',
    'Mercator Medical S.A.': 'MMD.WA',
    'Mercator Transport Group S.A.': 'MTR.WA',
    'Mercator Silver S.A.': 'MSR.WA',
    'Mieszko S.A.': 'MSK.WA',
    'Mkr Property S.A.': 'MKP.WA',
    'MLP Group S.A.': 'MLP.WA',
    'Mostostal Warszawa S.A.': 'MSW.WA',
    'Movema S.A.': 'MVA.WA',
    'Netia S.A.': 'NET.WA',
    'Newag S.A.': 'NWG.WA',
    'Notoria Serwis S.A.': 'NTS.WA',
    'Notowania.pl S.A.': 'NTW.WA',
    'Novakom S.A.': 'NOV.WA',
    'Oasis Group S.A.': 'OAS.WA',
    'OEX S.A.': 'OEX.WA',
    'Ogniwo S.A.': 'OGW.WA',
    'Orange Polska S.A.': 'OPL.WA',
    'Orbis S.A.': 'ORB.WA',
    'OTO Technology S.A.': 'OTO.WA',
    'Otwarte Fundusze Emerytalne Polskiego Banku Spółdzielczego S.A.': 'OFE.WA',
    'Paged S.A.': 'PGD.WA',
    'Pekabex S.A.': 'PKX.WA',
    'Pelion S.A.': 'PLN.WA',
    'Penta Investments S.A.': 'PNT.WA',
    'Play Communications S.A.': 'PLY.WA',
    'Polski Holding Nieruchomości S.A.': 'PHN.WA',
    'Polski Holding Obrony S.A.': 'PHO.WA',
    'Polski Koncern Naftowy ORLEN S.A.': 'PKN.WA',
    'Polwax S.A.': 'PLX.WA',
    'Polimex-Mostostal S.A.': 'PXM.WA'
}
