# WIG20 dictionary
WIG20 = {
    'Alior Bank S.A.': 'ALR.WA',
    'Allegro S.A.': 'ALE.WA',
    'Budimex S.A.': 'BDX.WA',
    'CD Projekt S.A.': 'CDR.WA',
    'Cyfrowy Polsat S.A.': 'CPS.WA',
    'Dino Polska S.A.': 'DNP.WA',
    'Jastrzębska Spółka Węglowa S.A.': 'JSW.WA',
    'Grupa Kety S.A.': 'KTY.WA',
    'KGHM Polska Miedź S.A.': 'KGH.WA',
    'Kruk S.A.': 'KRU.WA',
    'LPP S.A.': 'LPP.WA',
    'MBank S.A.': 'MBK.WA',
    'Orange Polska S.A.': 'OPL.WA',
    'Bank Polska Kasa Opieki S.A.': 'PEO.WA',
    'Pepco Group S.A.': 'PCO.WA',
    'PGE Polska Grupa Energetyczna S.A.': 'PGE.WA',
    'PKN Orlen S.A.': 'PKN.WA',
    'PKO Bank Polski S.A.': 'PKO.WA',
    'PZU S.A.': 'PZU.WA',
    'Santander Bank Polska S.A.': 'SPL.WA'
}

# mWIG40 dictionary
mWIG40 = {
    '11 bit studios S.A.': '11B.WA',
    'AB S.A.': 'ABE.WA',
    'ASBISc Enterprises Plc': 'ASB.WA',
    'AmRest Holdings SE': 'EAT.MC',
    'Arctic Paper S.A.': 'ARP.ST',
    'Asseco Poland S.A.': 'ASOZY',
    'Auto Partner S.A.': 'APR.WA',
    'Bank Handlowy w Warszawie SA': '0DOS.L',
    'Bank Millennium S.A.': 'MIL.WA',
    'Benefit Systems S.A.': 'BFT.WA',
    'CCC S.A.': 'CCC.WA',
    'CI Games SE': 'CIG.WA',
    'Cognor Holding S.A.': 'COG.WA',
    'Comarch S.A.': 'CMR.WA',
    'Develia S.A.': 'DVL.WA',
    'Dom Development S.A.': 'DOM.WA',
    'ENEA S.A.': 'ENA.WA',
    'Eurocash S.A.': 'EUR.WA',
    'Gielda Papierow Wartosciowych w Warszawie SA': 'GPW.WA',
    'GreenX Metals Limited': 'GRX.L',
    'Grenevia S.A.': 'GEA.WA',
    'Grupa Azoty S.A.': 'ATT.WA',
    'Grupa Pracuj S.A.': 'GPP.WA',
    'Huuuge, Inc.': 'HUG.WA',
    'ING Bank Slaski S.A.': 'ING.WA',
    'Inter Cars S.A.': 'CAR.WA',
    'Lubelski Wegiel Bogdanka SA': 'LWB.WA',
    'Mo-BRUK S.A.': 'MBR.WA',
    'NEUCA S.A.': 'NEU.WA',
    'Pkp Cargo S.A.': 'PKP.WA',
    'Polimex-Mostostal SA': 'PXM.WA',
    'Rainbow Tours SA': 'RBW.WA',
    'Ryvu Therapeutics S.A.': '9Y4.F',
    'Selvita S.A.': 'SLV.WA',
    'Synektik Spolka Akcyjna': 'SNT.WA',
    'TAURON Polska Energia SA': 'TPE.WA',
    'Ten Square Games SA': 'TEN.WA',
    'Text S.A.': 'TXT.WA',
    'Wirtualna Polska Holding SA': 'WPL.WA',
    'XTB S.A.': 'XTB.WA'
}

